import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    display: 'flex',
    height: '100%',
    backgroundColor: 'lightblue',
  },
  navBar: {
    flex: 1,
    display: 'flex',
    flexDirection: 'row',
    //justifyContent: 'space-between',
    height: '25%',
    backgroundColor: '#1E3461',
    paddingLeft: '5%',
  },
  header: {
    flex: 6,
    paddingTop: '17%',
    color: 'white',
    fontWeight: 'bold',
    fontSize: 30,
  },
  logoBox: {
    flex: 0.92,
    height: 50,
    width: 50,
    borderRadius: 50,
    overflow: 'hidden',
    top: '14%',
    right: '20%',
  },
  body: {
    flex: 5,
    diplay: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
  },
  input: {
    height: 50,
    width: '60%',
    paddingLeft: '3%',
    backgroundColor: 'white',
    borderColor: 'gray',
    borderWidth: 2,
    color: 'gray',
    fontSize: 20,
  },
  signIn: {
    height: '20%',
    width: '60%',
    margin: '5%',
    borderWidth: 10,
    borderColor: '#1E3461',
    borderLeftColor: '#427EC0',
    alignItems: 'center',
  },
  scrollVote: {
    display: 'flex',
    flexDirection: 'column',
    width: '80%',
  },
  openVote: {
    height: 150,
    backgroundColor: 'white',
    margin: 10,
    padding: '5%',
  },
  ballotInfo: {
    overflow: 'hidden',
  },
  buttonBox: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  voteYes: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'green',
  },
  voteNo: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'red',
  },
  voteAb: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'gray',
  },
  botBar: {
    flex: 0.7,
    display: 'flex',
    flexDirection: 'row',
    height: '20%',
    backgroundColor: '#427EC0',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  addBallot: {
    flex: 1,
    width: '170%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    borderWidth: 3,
    borderColor: 'black',
    borderTopWidth: 0,
  },
  addBalText: {
    fontWeight: 'bold',
    color: '#1E3461',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'white',
    position: 'absolute',
    height: '90%',
    width: '90%',
    zIndex: 1000,
  },
  bioInput: {
    height: '70%',
    width: '70%',
    paddingLeft: '3%',
    backgroundColor: 'white',
    borderColor: 'gray',
    borderWidth: 2,
    color: 'gray',
    fontSize: 20,
  },
  submit: {
    flex: 1,
    width: '70%',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 10,
    borderColor: 'black',
  },
  aTitle: {
    fontSize: 30,
  },
  footer: {
    fontSize: 30,
    color: 'white',
    fontWeight: 'bold',
    justifyContent: 'center',
  },
});
